FROM nginx:alpine

MAINTAINER hexseven <hexseven@nomadic.red>

RUN apk add nginx

COPY index.html /usr/share/nginx/html/index.html
COPY nomadic.png /usr/share/nginx/html/nomadic.png
COPY favicon.ico /usr/share/nginx/html/favicon.ico
