version: 0.2

phases:
  install:
    commands:
      - |
          set -ex
          env | sort
          ls -la
          pwd
          echo "
            stack_name ${APP_NAME}
            environment ${ENVIRONMENT}
            aws_region ${AWS_REGION}
            security_group_id ${SECGROUP_ID}
            nomadic_leader ${NOMADIC_LEADER}
          "

  build:
    commands:
      - |
          set -ex
          ls -la
          pwd
          cd warships/${APP_NAME}
          pwd
          echo deploy nomadic ${APP_NAME} ${ENVIRONMENT}
          PUBLIC_IP=$(curl ipecho.net/plain)
          echo ${SECGROUP_ID} ${PUBLIC_IP}
          aws ec2 authorize-security-group-ingress \
            --group-id ${SECGROUP_ID} \
            --protocol tcp \
            --port 22 \
            --cidr ${PUBLIC_IP}/32 || true

          echo "Host *" | tee ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" | tee -a ~/.ssh/config
          echo "  StrictHostKeyChecking no" | tee -a ~/.ssh/config

          echo configure private key
          aws ssm get-parameter \
            --region us-east-1 \
            --name nomadic_ssh_key \
            --with-decryption \
            --query Parameter.Value \
            --output text | tee ssh.key
          chmod -c 0400 ssh.key

          echo update nomad job
          ssh -i ssh.key ec2-user@${NOMADIC_LEADER} "\
            hostname && \
            git clone https://github.com/nand0p/nomadic.git && \
            cat nomadic/warships/containers/nomadic_frontpage/nomadic.hcl && \
            sudo nomad run nomadic/warships/containers/nomadic_frontpage/nomadic.hcl \
          "

          aws ec2 revoke-security-group-ingress \
            --group-id ${SECGROUP_ID} \
            --protocol tcp \
            --port 22 \
            --cidr ${PUBLIC_IP}/32
          rm -fv ssh.key

artifacts:
  files:
    - "**/*"
