version: 0.2

phases:
  install:
    commands:
      - |
          set -ex
          env | sort
          ls -la
          pwd
          echo "
            stack_name ${APP_NAME}
            environment ${ENVIRONMENT}
            aws_region ${AWS_REGION}
            security_group_id ${SECGROUP_ID}
            nomadic_leader ${NOMADIC_LEADER}
          "

  build:
    commands:
      - |
          set -ex
          ls -la
          pwd
          cd warships/${APP_NAME}
          pwd
          echo deploy nomadic ${APP_NAME} ${ENVIRONMENT}
          PUBLIC_IP=$(curl ipecho.net/plain)
          echo ${SECGROUP_ID} ${PUBLIC_IP}
          aws ec2 authorize-security-group-ingress \
            --group-id ${SECGROUP_ID} \
            --protocol tcp \
            --port 22 \
            --cidr ${PUBLIC_IP}/32 || true
          mkdir -pv /home/ec2-user/.ssh
          #echo "Host ${NOMADIC_LEADER}" | tee /home/ec2-user/.ssh/config
          #echo "  UserKnownHostsFile /dev/null" | tee -a /home/ec2-user/.ssh/config
          #echo "  StrictHostKeyChecking no" | tee -a /home/ec2-user/.ssh/config
          #echo "  User ec2-user" | tee -a /home/ec2-user/.ssh/config
          #echo "  IdentityFile /home/ec2-user/.ssh/ssh.key" | tee -a /home/ec2-user/.ssh/config
          #chmod -c 0400 /home/ec2-user/.ssh/config

          echo configure private key
          aws ssm get-parameter \
            --region us-east-1 \
            --name nomadic_ssh_key \
            --with-decryption \
            --query Parameter.Value \
            --output text | tee /home/ec2-user/.ssh/ssh.key
          chmod -c 0400 /home/ec2-user/.ssh/ssh.key

          echo deploy and or update nomad job
          ssh -v -i /home/ec2-user/.ssh/ssh.key -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ec2-user@${NOMADIC_LEADER} hostname

          #ssh -i /home/ec2-user/.ssh/ssh.key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  ec2-user@${NOMADIC_LEADER} git clone https://github.com/nand0p/nomadic.git /home/ec2-user/nomadic

          #ssh -i /home/ec2-user/.ssh/ssh.key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  ec2-user@${NOMADIC_LEADER} nomad run /home/ec2-user/nomadic/warships/containers/nomadic_frontpage/nomadic.hcl

  finally:
    - aws ec2 revoke-security-group-ingress \
        --region us-east-1 \
        --group-id ${SECGROUP_ID} \
        --protocol tcp \
        --port 22 \
        --cidr ${PUBLIC_IP}/32
    - rm -fv /home/ec2-user/.ssh/ssh.key

artifacts:
  files:
    - "**/*"
